version: '3.4'

services:
  mongo:
    image: aashreys/mongo-auth
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    healthcheck:
      test: curl -f http://localhost:27017 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  apollo-graphql-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rags:latest
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 3200:3100
